# Generated by Django 4.1.5 on 2023-01-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=25)),
                ("email", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "F"), ("M", "M")], max_length=2, null=True
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Frontend", "Frontend"),
                            ("Intern", "Intern"),
                            ("Fullstack", "Fullstack"),
                            ("Backend", "Backend"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
